version: "2"
services:
  ipfs:
    container_name: ipfs
    build: .
    ports:
      - "4001"
      - "4002/udp"
      - "172.20.0.1:5001:5001"
      - "172.20.0.1:8080:8080"
    volumes:
      - /var/ipfs:/home/ipfs
